// scripts/pages-data.ts

export const pages = [
  {
    title: "Bilgi",
    slug: "bilgi",
    content: "<p>Bilgi içerik sayfası.</p>",
    seo_title: "Bilgi - LenaCars",
    seo_description: "Bilgilendirici içerikler.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "lenacars-bilgilendiriyor",
    status: "published",
  },
  {
    title: "Basın Köşesi",
    slug: "basin-kosesi",
    content: "<p>Basın bültenleri ve duyurular.</p>",
    seo_title: "Basın Köşesi - LenaCars",
    seo_description: "Basın köşesi haberleri ve duyurular.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "basin-kosesi",
    status: "published",
  },
  {
    title: "Elektrikli Araçlar",
    slug: "elektrikli-araclar",
    content: "<p>Elektrikli araçlar hakkında bilgiler.</p>",
    seo_title: "Elektrikli Araçlar - LenaCars",
    seo_description: "Elektrikli araç dünyasına giriş yapın.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "elektrikli-araclar",
    status: "published",
  },
  {
    title: "İkinci El",
    slug: "ikinci-el",
    content: "<p>İkinci el araçlarımız burada.</p>",
    seo_title: "İkinci El Araçlar - LenaCars",
    seo_description: "Uygun fiyatlı ikinci el araçlar.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "ikinci-el",
    status: "published",
  },
  {
    title: "Kiralama",
    slug: "kiralama",
    content: "<p>Araç kiralama seçeneklerimiz hakkında bilgi.</p>",
    seo_title: "Araç Kiralama - LenaCars",
    seo_description: "Günlük ve uzun dönem araç kiralama hizmetleri.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "kiralama",
    status: "published",
  },
  {
    title: "Kurumsal",
    slug: "kurumsal",
    content: "<p>Kurumsal bilgilerimiz ve vizyonumuz.</p>",
    seo_title: "Kurumsal - LenaCars",
    seo_description: "LenaCars kurumsal vizyon ve misyonu.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "kurumsal",
    status: "published",
  },
  {
    title: "LenaCars Bilgilendiriyor",
    slug: "lenacars-bilgilendiriyor",
    content: "<p>Faydalı bilgiler ve duyurular.</p>",
    seo_title: "LenaCars Bilgilendiriyor",
    seo_description: "LenaCars faydalı bilgiler ve rehberler.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "lenacars-bilgilendiriyor",
    status: "published",
  },
  {
    title: "Nasıl Çalışır?",
    slug: "nasil-calisir",
    content: "<p>Kiralamalar ve süreçler nasıl çalışıyor?</p>",
    seo_title: "Nasıl Çalışır? - LenaCars",
    seo_description: "Araç kiralama süreçlerini öğrenin.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "lenacars-bilgilendiriyor",
    status: "published",
  },
  {
    title: "SSS (Sık Sorulan Sorular)",
    slug: "sss",
    content: "<p>Sık sorulan sorular ve cevaplar.</p>",
    seo_title: "Sık Sorulan Sorular - LenaCars",
    seo_description: "SSS bölümüyle merak ettiklerinizi öğrenin.",
    banner_image: "",
    thumbnail_image: "",
    menu_group: "kurumsal",
    status: "published",
  }
];
